<?php
require_once __DIR__ . '/include/web-config.php';
$pageTitle='Expense Payment List';
$headStyles=['https://cdn.datatables.net/1.13.8/css/jquery.dataTables.min.css','https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css'];
$headScripts=['https://code.jquery.com/jquery-3.7.1.min.js','https://cdn.datatables.net/1.13.8/js/jquery.dataTables.min.js','https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js','https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js','https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js','https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js','https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js','https://cdn.datatables.net/buttons/2.4.2/js/buttons.print.min.js'];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="<?php echo web_h(app_theme_color()); ?>"><title><?php echo web_h($pageTitle); ?> · <?php echo web_h(app_name()); ?></title><?php render_frontend_config_script(); ?><script src="assets/js/runtime.js"></script><?php foreach($headStyles as $u):?><link rel="stylesheet" href="<?php echo htmlspecialchars($u,ENT_QUOTES,'UTF-8');?>"><?php endforeach;?><link rel="stylesheet" href="assets/css/core.css"><link rel="stylesheet" href="assets/css/components.css"><link rel="stylesheet" href="assets/css/theme.css"><script src="https://unpkg.com/lucide@0.468.0/dist/umd/lucide.min.js" defer></script><?php foreach($headScripts as $u):?><script src="<?php echo htmlspecialchars($u,ENT_QUOTES,'UTF-8');?>"></script><?php endforeach;?></head>
<body><div class="app-shell"><?php require __DIR__.'/include/sidebar.php';?><main class="main-stage"><?php require __DIR__.'/include/topbar.php';?><section class="page-content"><script src="assets/js/toaster.js"></script><script src="assets/js/app.js"></script><script src="assets/js/theme.js"></script><script src="assets/js/layout.js"></script><script src="assets/js/datatable.js"></script>
<div class="page-head"><div><h1>Expense Payment List</h1><p>Posted Expense Payments. Edit/Delete automatically reverses the old payment effect and recalculates the Expense.</p></div><a class="btn btn-primary" id="addButton" href="expense-payment.php"><i data-lucide="plus"></i>Add Payment</a></div>
<div class="card table-card"><div class="card-header"><div class="form-row" style="width:100%;margin:0;"><div class="field col-4"><label for="paymentSearch">Search</label><input id="paymentSearch" type="text" placeholder="Search payment, expense, payee..."></div><div class="field col-4"><label for="dateFrom">From Date</label><input id="dateFrom" type="date"></div><div class="field col-4"><label for="dateTo">To Date</label><input id="dateTo" type="date"></div></div></div><div class="table-scroll"><table id="paymentTable" class="display data-table" style="width:100%"><thead><tr><th>Payment No</th><th>Payment Date</th><th>Expense No</th><th>Category</th><th>Payee</th><th>Amount</th><th>Manage</th></tr></thead></table></div></div>
<script>
(function($){'use strict';if(!window.AppDataTable||!AppDataTable.ensureAvailable())return;var listActions=[],formActions=[],has=AppDataTable.has,searchTimer=null;function esc(v){return $('<div>').text(v==null?'':String(v)).html();}function money(v){return'₹'+Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});}
var table=AppDataTable.init('#paymentTable',{serverSide:true,searching:true,appSearch:false,pageLength:10,lengthMenu:[[10,25,50,100],[10,25,50,100]],order:[[1,'desc']],scrollX:true,autoWidth:false,buttons:[{extend:'copyHtml5',text:'Copy',title:'Expense Payments',action:AppDataTable.serverSideExportAction,exportOptions:{columns:[0,1,2,3,4,5]}},{extend:'csvHtml5',text:'CSV',title:'Expense Payments',action:AppDataTable.serverSideExportAction,exportOptions:{columns:[0,1,2,3,4,5]}},{extend:'excelHtml5',text:'Excel',title:'Expense Payments',action:AppDataTable.serverSideExportAction,exportOptions:{columns:[0,1,2,3,4,5]}},{extend:'pdfHtml5',text:'PDF',title:'Expense Payments',orientation:'landscape',pageSize:'A4',action:AppDataTable.serverSideExportAction,exportOptions:{columns:[0,1,2,3,4,5]}},{extend:'print',text:'Print',title:'Expense Payments',action:AppDataTable.serverSideExportAction,exportOptions:{columns:[0,1,2,3,4,5]}}],ajax:function(data,cb){var p=new URLSearchParams();p.set('datatable','1');p.set('draw',data.draw);p.set('start',data.start);p.set('length',data.length);p.set('search[value]',data.search.value||'');p.set('date_from',document.getElementById('dateFrom').value);p.set('date_to',document.getElementById('dateTo').value);if(data.order&&data.order[0]){p.set('order[0][column]',data.order[0].column);p.set('order[0][dir]',data.order[0].dir);}App.api('api/expense-payments.php?'+p.toString()).then(function(r){listActions=(r.data.list_actions||[]).map(Number);formActions=(r.data.form_actions||[]).map(Number);document.getElementById('addButton').style.display=has(formActions,2)?'inline-flex':'none';AppDataTable.applyExportPermissions(table,listActions);cb(r.data.datatable);}).catch(function(e){App.showError(e,'Unable to load Expense Payments.');cb({draw:data.draw,recordsTotal:0,recordsFiltered:0,data:[]});});},columns:[{data:'payment_no',defaultContent:'-'},{data:'payment_date',defaultContent:'-'},{data:'expense_no',defaultContent:'-'},{data:'category_name',defaultContent:'-'},{data:'payee_name',defaultContent:'-'},{data:'amount',className:'dt-body-right',render:function(v,t){return t==='display'?money(v):Number(v||0);}},{data:null,orderable:false,searchable:false,className:'table-action-icons',render:function(d,t,r){if(t!=='display')return'';var a=[];if(has(formActions,3))a.push(App.iconActionHtml({href:r.edit_url,icon:'pencil',label:'Edit Expense Payment'}));else a.push(App.iconActionHtml({href:r.view_url,icon:'eye',label:'View Expense Payment'}));if(has(formActions,4))a.push('<button type="button" class="table-icon-action delete-payment" data-ref="'+esc(r.ref)+'" title="Delete Expense Payment" aria-label="Delete Expense Payment"><i data-lucide="trash-2"></i></button>');return a.join(' ');}}],drawCallback:function(){if(window.lucide)window.lucide.createIcons();}});
(function(){var e=document.getElementById('paymentTable'),card=e?e.closest('.table-card'):null,row=card?card.querySelector('.app-table-search-row'):null;if(row)row.remove();})();
var q=document.getElementById('paymentSearch');q.addEventListener('input',function(){clearTimeout(searchTimer);searchTimer=setTimeout(function(){table.search(q.value.trim()).draw();},300);});['dateFrom','dateTo'].forEach(function(id){document.getElementById(id).addEventListener('change',function(){table.ajax.reload();});});document.getElementById('paymentTable').addEventListener('click',function(e){var b=e.target.closest('.delete-payment');if(!b)return;if(!window.confirm('Delete this Expense Payment? The Expense Paid/Balance/Status will be recalculated automatically.'))return;b.disabled=true;App.api('api/expense-payments.php',{method:'POST',body:{action:'delete',ref:b.dataset.ref}}).then(function(r){showToast(r.message||'Expense Payment deleted.',{type:'success',duration:2});table.ajax.reload(null,false);}).catch(function(err){b.disabled=false;App.showError(err,'Unable to delete Expense Payment.');});});
})(jQuery);
</script></section><?php require __DIR__.'/include/footer.php';?></main></div><script>if(window.lucide){window.lucide.createIcons();}</script></body></html>
